### ISSUE TITLE
Lag and/or missed keystrokes 

### ISSUE THREAD

**Issue by aikiharp** [andreasbrett/OVLP#2]
Hi, I built this pedal this week. Thank you so much for the layout and instructions!

I'm having a problem on YouTube for Chrome on Mac Sonoma. Sometimes the footswitches elicit an immediate response from YouTube, sometimes there's a delay in response, and sometimes there's no response at all. I'm new to Arduino and GreaseMonkey, so I'm not sure how to troubleshoot. 

I wonder if the GreaseMonkey script is causing lag? It appears all the functions in your design are covered by native YouTube keyboard shortcuts, except looping. I wonder if the pedal would bebe more responsive by sending the YouTube native keystrokes directly instead of via GreaseMonkey? I'd have to find a solution for the looping function though. 

Any other ideas about the source of lag and/or missed keystrokes? 

Thank you again for the project. It was fun to build.  I'm surprised I'm the first to post here since it seems like something super useful.

**Comment by andreasbrett** [comment]
Thanks for the feedback. Great to finally see someone using it. I haven't tested OVLP with a Mac to be honest but it's great to hear that it (at least partially) works. There are 2 things you could try:

1) extend or shorten the timings for a short press here: https://github.com/andreasbrett/OVLP/blob/414867798e9a0afab297b07d95b6abdcb45052e1/Arduino/OVLP/OVLP.ino#L32

2) modify the greasemonkey script and comment out the following if-block. This will keep the native youtube key map for play. If that fixes the issue for the play button, it is the greasemonkey script and I will need to debug. I don't think so though. https://github.com/andreasbrett/OVLP/blob/414867798e9a0afab297b07d95b6abdcb45052e1/Tampermonkey/OVLP.user.js#L148

**Comment by ImCoKeMaN** [comment]
Just letting you know someone else uses this!  I use it on PC and haven't had the missed key issues, I did a few adjustments to use internal arduino resistors and changed a key combo or 2 due to conflicts, but it's been working great for youtube videos.

**Comment by aikiharp** [comment]
Thanks for the suggestions. I'm new to Arduino, so I don't want to mess with the .ino file too much. 

1. @andreasbrett, I adjusted the short and long press timings (both longer and shorter), but couldn't discern a repeatable pattern. At any duration, the keys seem to work OK on the first press, but start lagging or become unresponsive after that.
2. I commented out the play/pause block in the Greasemonkey script. That didn't seem to affect the behavior at all.
3. I installed Tampermonkey in a couple other Mac-version browsers: Firefox and Opera, both with no other extensions installed--my Chrome instance has a lot of extensions. Again, no difference in behavior. Are the "monkey" extensions all the same, or would it be worth trying a different one?

For troubleshooting, can you suggest a strategy to determine if the issue is with the [Pro Micro](https://www.amazon.com/gp/product/B012FOV17O) I have, my wiring, the USB bus, the .ino file (specific to Mac), the Greasemonkey script, or the browser? It seems like it should work the same on Mac as on Windows, so I'm kind of stumped. I've got a Windows VM I can test on to see if it works better there, but it's still passing through the Mac OS at some level.

Thanks again for your work on this! It's the only alternative to the commercial pedals I've seen, so I'd love to get it working. I wonder what controller the commercial version(s) use? I haven't seen schematic for those.

**Comment by aikiharp** [comment]
@ImCoKeMaN 

>  I did a few adjustments to use internal Arduino resistors 

What was the rationale for using the internal (pullup?) resistors, and what's the impact if we don't? Again, I'm new to Arduino so I'm trying to learn as much as I can.

**Comment by ImCoKeMaN** [comment]
I just knew my arduino had pullup resistors and didn't want to wire in additional components (didn't have enough resistors lying around either)  only a few changes are needed for it, but if you're not familiar might not be worth the change since the code/wiring/project was already documented fairly completely
sample edits:
pinMode(IN_pin_button, INPUT **_PULLUP**);
and reverse the high/low logic
if (currentState == **LOW**)   //instead of HIGH
and
 if (digitalRead(pin_bank) == **HIGH**) {


If you do want to change anything make sure you have it working first before throwing in additional variables to the troubleshooting =)

**Comment by aikiharp** [comment]
> I just knew my arduino had pullup resistors and didn't want to wire in additional components (didn't have enough resistors lying around either) only a few changes are needed for it, but if you're not familiar might not be worth the change since the code/wiring/project was already documented fairly completely sample edits: pinMode(IN_pin_button, INPUT **_PULLUP**); and reverse the high/low logic if (currentState == **LOW**) //instead of HIGH and if (digitalRead(pin_bank) == **HIGH**) {
> 
> If you do want to change anything make sure you have it working first before throwing in additional variables to the troubleshooting =)

Oh, OK. I built the pedal with 10K resistors inline with the ground (as pictured in the readme). I assume they do the same job as the built-in pullup resistors?

**Comment by ImCoKeMaN** [comment]
Same function just in reverse resistor to ground is a pull down that's why I needed to make the code changes to adapt as well.

**Comment by aikiharp** [comment]
@andreasbrett I think my problem is getting the duration for the short press in OVLP.ino to correctly match what my foot is doing, and vice-versa. It seems pretty sensitive to the timing--is there a way to set a range from 10ms to 50ms for the short press and 300-600ms for long press (or similar)?  Also, I don't use the midi function but I wired the switch in anyway. Any suggestions on what I could do with the other bank?

**Comment by andreasbrett** [comment]
@aikiharp we could of course change the code to allow ranges of 10-50ms for short press and 300-600ms for long press but what happens with presses of 51-299ms duration? IMHO it's bad UX to have a gap between short and long press ranges. 

Looking at my comment from back then, I think you might have gotten the wrong idea how short and long presses are distinguished in OVLP. A button needs to be pressed AT LEAST 30ms to be actually considered a button press. If it had been pressed for 30-449ms it is a short press. If it is 450ms or more it is a long press.
https://github.com/andreasbrett/OVLP/blob/414867798e9a0afab297b07d95b6abdcb45052e1/Arduino/OVLP/OVLP.ino#L32-L33

Changing the parameters to 10 and 300 should roughly result in what you requested. I would not go as low as 10ms though as you won't be able to physically press that quickly (especially not with feet) and it increases risk of bouncing (see: https://docs.arduino.cc/built-in-examples/digital/Debounce). I chose 30ms which is already quite low considering the Arduino example uses 50ms.

**Comment by andreasbrett** [comment]
To find good values you can set `logMessages` to `true` (see [here](https://github.com/andreasbrett/OVLP/blob/6d8ae96e3c8f0b29a78eafc8fcb712087c45f027/Arduino/OVLP/OVLP.ino#L34)) and watch the serial monitor in Arduino IDE. You should get valuable info how your button presses were interpreted. Use the latest code (published a minute ago) to also see timings like this:

![image](https://github.com/andreasbrett/OVLP/assets/6610451/da361258-df8d-48c7-9be0-a3962adf9960)

**Comment by aikiharp** [comment]
@andreasbrett This is great info, and very helpful! I enabled serial logging and there's some weirdness going on with the board and/or the switches: 


```
---------------------------------------------
Serial interface initialized.
Initializing USB HID interface...
Initializing USB MIDI interface...
Initializing buttons...
Initialized button on pin 5
Initialized button on pin 6
Initialized button on pin 7
Initialized button on pin 8
Initialized button on pin 9
Initialized button on pin 10
Initialization done. Running loop now.
---------------------------------------------

Button press detected...
 - hold time = 0ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 0ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 0ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 5ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 6ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 7ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 6ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 6ms
 -> bounced. ignoring.
Button press detected...
 - hold time = 15ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 132ms
 - bank = 2
 - type = short
 - sending MIDI-PC#5
 - hold time = 114ms
 - bank = 2
 - type = short
 - sending MIDI-PC#3

Button press detected...
 - hold time = 8ms
 -> bounced. ignoring.
```


All of the ignored presses are without touching the switches. The 2nd to last is where I did press one of the switches and it's reading the output. Mechanical problem? Next step will be to test all the switches for continuity to see if one or more is sending these "ghost presses."

Any other troubleshooting advice is greatly appreciated.

**Comment by aikiharp** [comment]
OK I got it. The ghost presses were from switches that had lost their R10K+ground connection. With installing everything in an enclosure, some of the connections must have broken off the switches. Now everything is properly connected and I'm getting 99% of the button presses with only a few ghost presses, which may just be from the physical movement of the switch: 

```
---------------------------------------------
Serial interface initialized.
Initializing USB HID interface...
Initializing USB MIDI interface...
Initializing buttons...
Initialized button on pin 5
Initialized button on pin 6
Initialized button on pin 7
Initialized button on pin 8
Initialized button on pin 9
Initialized button on pin 10
Initialization done. Running loop now.
---------------------------------------------

Button press detected...
 - hold time = 129ms
 - bank = 1
 - type = short
 - sending Shift#Alt#A

Button press detected...
 - hold time = 135ms
 - bank = 1
 - type = short
 - sending Shift#Alt#S

Button press detected...
 - hold time = 0ms
 -> bounced. ignoring.

Button press detected...
 - hold time = 113ms
 - bank = 1
 - type = short
 - sending Shift#Alt#D
```
The 2nd to last entry is one of the remaining ghost presses but I don't think it affects anything.

Again, thanks VERY much for the code, design, and support!

**Comment by andreasbrett** [comment]
Awesome! Glad this got solved and we now know OVLP works as intended on MacOS as well!
